version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bookmate-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_platform
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: bookmate-auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  booking-service:
    build: ./booking-service
    container_name: bookmate-booking-service
    env_file:
      - ./booking-service/.env
    ports:
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: bookmate-frontend
    ports:
      - "3000:80"   # host 3000 → container 80
    depends_on:
      auth-service:
        condition: service_started
      booking-service:
        condition: service_started

volumes:
  postgres_data:
